### ISSUE TITLE
how to use  test  using nsai.executor.relate

### ISSUE THREAD

**Issue by mindmad** [nerdimite/neuro-symbolic-ai-soc#1]
Hello, 
I tried to implement using the Colab, and now I want to test it with different questions. like using nsai.executor.relate and the rest.
I tried using the following : 

`program = nsai.sem_parser.predict('What is the furthest shape from the green object? ')
program`

> ['filter green', 'relate furthest', 'query shape']

`nsai.executor.relate(nsai.executor.filter_(nsai.executor.query(nsai.executor.filter_('green'), 'shape')),program)`

> UnboundLocalError                         Traceback (most recent call last)
> <ipython-input-75-674241ff2f68> in <module>()
>       1 # nsai.executor.count(nsai.executor.filter_(nsai.executor.query(nsai.executor.filter_('green'), 'shape')))
> ----> 2 nsai.executor.relate(nsai.executor.filter_(nsai.executor.query(nsai.executor.filter_('green'), 'shape')),program)
> 
> /content/neuro-symbolic-ai-soc/program_executor.py in relate(self, obj, param)
>      50 
>      51         # Get the object from the scene of that index
> ---> 52         req_obj = self.scene[self.scene.index == idx]
>      53 
>      54         return req_obj
> 
> UnboundLocalError: local variable 'idx' referenced before assignment

I don't know which parameter to use for the relate function, if possible can you make example for the test>

**Comment by nerdimite** [comment]
Hi @mindmad,
The relate function takes either `closest` or `furthest` as a parameter. An example for your case will look like this
```python
program = nsai.sem_parser.predict('What is the furthest shape from the green object?')
program
> ['filter green', 'relate furthest', 'query shape']

nsai.executor.query(nsai.executor.relate(nsai.executor.filter_('green'), 'furthest'), 'shape')
>'circle'
```
Let me know if you have any more questions :). If not you can close this issue.
